<a href="https://colab.research.google.com/github/beena24/Research_works/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data=pd.Series([10,20,30,40,50,60,70])
print(data)

0    10
1    20
2    30
3    40
4    50
5    60
6    70
dtype: int64

In [ ]:
data.index

RangeIndex(start=0, stop=7, step=1)

In [ ]:
data.values

array([10, 20, 30, 40, 50, 60, 70])

In [ ]:
data_series={'column1':pd.Series([100,200,300,400,500,600,700]),
             'column2':pd.Series([10,20,30,40,50,60,70])}
print(data_series)

{'column1': 0    100
1    200
2    300
3    400
4    500
5    600
6    700
dtype: int64, 'column2': 0    10
1    20
2    30
3    40
4    50
5    60
6    70
dtype: int64}

In [ ]:
pd.DataFrame(data_series)

   column1  column2
0      100       10
1      200       20
2      300       30
3      400       40
4      500       50
5      600       60
6      700       70

In [ ]:
movies_df=pd.read_csv("https://raw.githubusercontent.com/ammishra08/MachineLearning/master/Datasets/movies.csv",sep=',')
display(movies_df)

,Film,Genre,Lead Studio,Audience score %,Profitability,Rotten Tomatoes %,Worldwide Gross,Year
0,Zack and Miri Make a Porno,Romance,The Weinstein Company,70,1.747542,64,$41.94,2008
1,Youth in Revolt,Comedy,The Weinstein Company,52,1.090000,68,$19.62,2010
2,You Will Meet a Tall Dark Stranger,Comedy,Independent,35,1.211818,43,$26.66,2010
3,When in Rome,Comedy,Disney,44,0.000000,15,$43.04,2010
4,What Happens in Vegas,Comedy,Fox,72,6.267647,28,$219.37,2008
...,...,...,...,...,...,...,...,...
72,Across the Universe,romance,Independent,84,0.652603,54,$29.37,2007
73,A Serious Man,Drama,Universal,64,4.382857,89,$30.68,2009
74,A Dangerous Method,Drama,Independent,89,0.448645,79,$8.97,2011
75,27 Dresses,Comedy,Fox,71,5.343622,40,$160.31,2008
76,(500) Days of Summer,comedy,Fox,81,8.096000,87,$60.72,2009

In [ ]:
movies_df.head()

,Film,Genre,Lead Studio,Audience score %,Profitability,Rotten Tomatoes %,Worldwide Gross,Year
0,Zack and Miri Make a Porno,Romance,The Weinstein Company,70,1.747542,64,$41.94,2008
1,Youth in Revolt,Comedy,The Weinstein Company,52,1.090000,68,$19.62,2010
2,You Will Meet a Tall Dark Stranger,Comedy,Independent,35,1.211818,43,$26.66,2010
3,When in Rome,Comedy,Disney,44,0.000000,15,$43.04,2010
4,What Happens in Vegas,Comedy,Fox,72,6.267647,28,$219.37,2008

In [ ]:
movies_df.tail()

,Film,Genre,Lead Studio,Audience score %,Profitability,Rotten Tomatoes %,Worldwide Gross,Year
72,Across the Universe,romance,Independent,84,0.652603,54,$29.37,2007
73,A Serious Man,Drama,Universal,64,4.382857,89,$30.68,2009
74,A Dangerous Method,Drama,Independent,89,0.448645,79,$8.97,2011
75,27 Dresses,Comedy,Fox,71,5.343622,40,$160.31,2008
76,(500) Days of Summer,comedy,Fox,81,8.096000,87,$60.72,2009

In [ ]:
stock_data=pd.read_excel("https://github.com/ammishra08/MachineLearning/blob/master/Datasets/data_akbilgic.xlsx?raw=true",header=1)

/usr/local/lib/python3.7/dist-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

In [ ]:
stock_data

,date,ISE,ISE.1,SP,DAX,FTSE,NIKKEI,BOVESPA,EU,EM
0,2009-01-05,0.035754,0.038376,-0.004679,0.002193,0.003894,0.000000,0.031190,0.012698,0.028524
1,2009-01-06,0.025426,0.031813,0.007787,0.008455,0.012866,0.004162,0.018920,0.011341,0.008773
2,2009-01-07,-0.028862,-0.026353,-0.030469,-0.017833,-0.028735,0.017293,-0.035899,-0.017073,-0.020015
3,2009-01-08,-0.062208,-0.084716,0.003391,-0.011726,-0.000466,-0.040061,0.028283,-0.005561,-0.019424
4,2009-01-09,0.009860,0.009658,-0.021533,-0.019873,-0.012710,-0.004474,-0.009764,-0.010989,-0.007802
...,...,...,...,...,...,...,...,...,...,...
531,2011-02-16,0.008599,0.013400,0.006238,0.001925,0.007952,0.005717,0.018371,0.006975,0.003039
532,2011-02-17,0.009310,0.015977,0.003071,-0.001186,0.000345,0.002620,0.001686,-0.000581,0.001039
533,2011-02-18,0.000191,-0.001653,0.001923,0.002872,-0.000723,0.000568,0.005628,0.000572,0.006938
534,2011-02-21,-0.013069,-0.013706,-0.020742,-0.014239,-0.011275,0.001358,-0.011942,-0.012615,-0.000958
535,2011-02-22,-0.007246,-0.019442,0.000000,-0.000473,-0.002997,-0.017920,-0.012252,-0.005465,-0.014297

In [ ]:
pd.read_excel

In [ ]:
stock_data.shape

(536, 10)

In [ ]:
movies_df.columns

Index(['Film', 'Genre', 'Lead Studio', 'Audience score %', 'Profitability',
       'Rotten Tomatoes %', 'Worldwide Gross', 'Year'],
      dtype='object')

In [ ]:
len(movies_df.columns)

8

In [ ]:
movies_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Film               77 non-null     object
 1   Genre              77 non-null     object
 2   Lead Studio        77 non-null     object
 3   Audience score %   77 non-null     int64
 4   Profitability      77 non-null     float64
 5   Rotten Tomatoes %  77 non-null     int64
 6   Worldwide Gross    77 non-null     object
 7   Year               77 non-null     int64
dtypes: float64(1), int64(3), object(4)
memory usage: 4.9+ KB

In [ ]:
movies_df['Profitability'].sort_values()

3      0.000000
33     0.000000
57     0.000000
8      0.005000
42     0.252895
        ...
12    10.180027
7     11.089742
14    14.196400
60    22.913136
68    66.934000
Name: Profitability, Length: 77, dtype: float64

In [ ]:
movies_df.sort_values(by ='Audience score %', ascending = False)

,Film,Genre,Lead Studio,Audience score %,Profitability,Rotten Tomatoes %,Worldwide Gross,Year
74,A Dangerous Method,Drama,Independent,89,0.448645,79,$8.97,2011
6,WALL-E,Animation,Disney,89,2.896019,96,$521.28,2008
22,Tangled,Animation,Disney,88,1.365692,89,$355.01,2010
39,My Week with Marilyn,Drama,The Weinstein Company,84,0.825800,83,$8.26,2011
72,Across the Universe,romance,Independent,84,0.652603,54,$29.37,2007
...,...,...,...,...,...,...,...,...
55,Killers,Action,Lionsgate,45,1.245333,11,$93.40,2010
3,When in Rome,Comedy,Disney,44,0.000000,15,$43.04,2010
18,The Heartbreak Kid,Comedy,Paramount,41,2.129444,30,$127.77,2007
48,Love Happens,Drama,Universal,40,2.004444,18,$36.08,2009
2,You Will Meet a Tall Dark Stranger,Comedy,Independent,35,1.211818,43,$26.66,2010

In [ ]:
movies_df[movies_df.duplicated()]

,Film,Genre,Lead Studio,Audience score %,Profitability,Rotten Tomatoes %,Worldwide Gross,Year
46,Mamma Mia!,Comedy,Universal,76,9.234454,53,$609.47,2008
65,Gnomeo and Juliet,Animation,Disney,52,5.387972,56,$193.97,2011

In [ ]:
movies_df.drop_duplicates(inplace=True)

In [ ]:
print(movies_df)

                                  Film    Genre            Lead Studio  \
0           Zack and Miri Make a Porno  Romance  The Weinstein Company
1                      Youth in Revolt   Comedy  The Weinstein Company
2   You Will Meet a Tall Dark Stranger   Comedy            Independent
3                         When in Rome   Comedy                 Disney
4                What Happens in Vegas   Comedy                    Fox
..                                 ...      ...                    ...
72                 Across the Universe  romance            Independent
73                       A Serious Man    Drama              Universal
74                  A Dangerous Method    Drama            Independent
75                          27 Dresses   Comedy                    Fox
76                (500) Days of Summer   comedy                    Fox

    Audience score %  Profitability  Rotten Tomatoes % Worldwide Gross  Year
0                 70       1.747542                 64         $41.94   2008
1                 52       1.090000                 68         $19.62   2010
2                 35       1.211818                 43         $26.66   2010
3                 44       0.000000                 15         $43.04   2010
4                 72       6.267647                 28        $219.37   2008
..               ...            ...                ...             ...   ...
72                84       0.652603                 54         $29.37   2007
73                64       4.382857                 89         $30.68   2009
74                89       0.448645                 79          $8.97   2011
75                71       5.343622                 40        $160.31   2008
76                81       8.096000                 87         $60.72   2009

[75 rows x 8 columns]

In [ ]:
movies_df.drop([0,2,3,5,6,8],axis=0)

,Film,Genre,Lead Studio,Audience score %,Profitability,Rotten Tomatoes %,Worldwide Gross,Year
1,Youth in Revolt,Comedy,The Weinstein Company,52,1.090000,68,$19.62,2010
4,What Happens in Vegas,Comedy,Fox,72,6.267647,28,$219.37,2008
7,Waitress,Romance,Independent,67,11.089742,89,$22.18,2007
9,Valentine's Day,Comedy,Warner Bros.,54,4.184038,17,$217.57,2010
10,Tyler Perry's Why Did I get Married,Romance,Independent,47,3.724192,46,$55.86,2007
...,...,...,...,...,...,...,...,...
72,Across the Universe,romance,Independent,84,0.652603,54,$29.37,2007
73,A Serious Man,Drama,Universal,64,4.382857,89,$30.68,2009
74,A Dangerous Method,Drama,Independent,89,0.448645,79,$8.97,2011
75,27 Dresses,Comedy,Fox,71,5.343622,40,$160.31,2008
76,(500) Days of Summer,comedy,Fox,81,8.096000,87,$60.72,2009

In [ ]:
movies_df.drop(['Lead Studio','Audience score %','Rotten Tomatoes %'], axis=1)

,Film,Genre,Profitability,Worldwide Gross,Year
0,Zack and Miri Make a Porno,Romance,1.747542,$41.94,2008
1,Youth in Revolt,Comedy,1.090000,$19.62,2010
2,You Will Meet a Tall Dark Stranger,Comedy,1.211818,$26.66,2010
3,When in Rome,Comedy,0.000000,$43.04,2010
4,What Happens in Vegas,Comedy,6.267647,$219.37,2008
...,...,...,...,...,...
72,Across the Universe,romance,0.652603,$29.37,2007
73,A Serious Man,Drama,4.382857,$30.68,2009
74,A Dangerous Method,Drama,0.448645,$8.97,2011
75,27 Dresses,Comedy,5.343622,$160.31,2008
76,(500) Days of Summer,comedy,8.096000,$60.72,2009

In [ ]:
movies_df.loc[10:20]

,Film,Genre,Lead Studio,Audience score %,Profitability,Rotten Tomatoes %,Worldwide Gross,Year
10,Tyler Perry's Why Did I get Married,Romance,Independent,47,3.724192,46,$55.86,2007
11,Twilight: Breaking Dawn,Romance,Independent,68,6.383364,26,$702.17,2011
12,Twilight,Romance,Summit,82,10.180027,49,$376.66,2008
13,The Ugly Truth,Comedy,Independent,68,5.402632,14,$205.30,2009
14,The Twilight Saga: New Moon,Drama,Summit,78,14.196400,27,$709.82,2009
15,The Time Traveler's Wife,Drama,Paramount,65,2.598205,38,$101.33,2009
16,The Proposal,Comedy,Disney,74,7.867500,43,$314.70,2009
17,The Invention of Lying,Comedy,Warner Bros.,47,1.751351,56,$32.40,2009
18,The Heartbreak Kid,Comedy,Paramount,41,2.129444,30,$127.77,2007
19,The Duchess,Drama,Paramount,68,3.207850,60,$43.31,2008
20,The Curious Case of Benjamin Button,Fantasy,Warner Bros.,81,1.783944,73,$285.43,2008